local f=assert(io.open('tests/tactics_traversal_probe.lua'));local s=f:read('*a');f:close()
local fragment=assert(s:match('(local function rejectedMove.-\nend)'))
local rejected=assert(load(fragment..'\nreturn rejectedMove'))()
local before={x=10,y=20,z=30,move=3,action=1}
assert(rejected(before,10,20,30,3,1,1),'unchanged open preview must be cancelled')
assert(not rejected(before,11,20,30,3,1,1),'executed displacement must not be cancelled')
assert(not rejected(before,10,20,30,2,1,1),'charged movement must not be classified as uncommitted')
assert(not rejected(before,10,20,30,3,0,1),'spent action must not be classified as uncommitted')
assert(not rejected(before,10,20,30,3,1,0),'closed preview must not receive field B input')
assert(s:find("pressNative(2);best=nil;index=1;phase='release';nextFrame=f+4;return",1,true),'rejected preview must reset the real scan')
local policy=s:sub(assert(s:find('local rejectedOrigin',1,true)),assert(s:find('local function rejectedMove',1,true))-1)
local avoid,mark=assert(load(policy..'\nreturn rejectedDirectionAt,rejectDirectionAt'))()
assert(not avoid(10,20,30,16),'new position must allow native direction')
mark(10,20,30,16)
assert(avoid(10,20,30,16),'rejected direction must not be retried at identical position')
assert(not avoid(10,20,30,32),'alternative direction must remain selectable')
mark(10,20,30,32)
assert(avoid(10,20,30,16) and avoid(10,20,30,32),'multiple rejections must survive rescanning')
assert(not avoid(11,20,30,16),'native displacement must restore direction eligibility')
assert(not avoid(10,20,30,32),'returning after displacement must permit fresh validation')
assert(s:find('not rejectedDirections[dirs[index]]',1,true),'native candidate scan must use rejection policy')
print('rejected move: cancellation, costs, direction alternatives and displacement recovery passed')
