"""Compile generated Rally poses against the approved native palette.
Retains source unchanged; chroma-key mask is part of native asset compilation.
"""
from pathlib import Path
import hashlib,json,re
from PIL import Image
root=Path('tactics/character-assets/rally');source=root/'states-source-v3.png'
header=(root/'rally_data.h').read_text()
palette=[int(v,0) for v in re.search(r'sRallyPalette\[16\] = \{(.*?)\}',header).group(1).split(',')]
colors=[((v&31)*255//31,((v>>5)&31)*255//31,((v>>10)&31)*255//31) for v in palette]
im=Image.open(source).convert('RGB');crops=[]
for row in range(2):
 for col in range(3):
  crop=im.crop((round(col*im.width/3),(0 if row==0 else round(im.height*0.52)),round((col+1)*im.width/3),(round(im.height*0.52) if row==0 else im.height)))
  mask=Image.new('L',crop.size)
  mask.putdata([0 if g>90 and g>r*1.6 and g>b*1.6 else 255 for r,g,b in crop.getdata()])
  bounds=mask.getbbox();assert bounds and bounds[0]>0 and bounds[1]>0 and bounds[2]<crop.width and bounds[3]<crop.height,'sprite touches cell gutter'
  crops.append((crop.crop(bounds),mask.crop(bounds)))
scale=min(44/max(c.height for c,m in crops),32/max(c.width for c,m in crops))
atlas=Image.new('P',(96,128));atlas.putpalette([channel for color in colors for channel in color]+[0]*(768-48))
for frame,(crop,mask) in enumerate(crops):
 size=(max(1,round(crop.width*scale)),max(1,round(crop.height*scale)))
 crop=crop.resize(size,Image.Resampling.NEAREST);mask=mask.resize(size,Image.Resampling.NEAREST)
 x0=(frame%3)*32+(32-crop.width)//2;y0=(frame//3)*64+56-crop.height
 for y in range(crop.height):
  for x in range(crop.width):
   if not mask.getpixel((x,y)):continue
   pixel=crop.getpixel((x,y));nearest=min(range(1,16),key=lambda i:sum((colors[i][c]-pixel[c])**2 for c in range(3)))
   atlas.putpixel((x0+x,y0+y),nearest)
atlas.info['transparency']=0;atlas.save(root/'rally-states-native.png')
tiles=[]
for frame in range(6):
 x0=(frame%3)*32;y0=(frame//3)*64
 assert atlas.crop((x0,y0,x0+32,y0+64)).getbbox()[3]==56
 for ty in range(8):
  for tx in range(4):
   for y in range(8):
    for x in range(0,8,2):tiles.append(atlas.getpixel((x0+tx*8+x,y0+ty*8+y))|(atlas.getpixel((x0+tx*8+x+1,y0+ty*8+y))<<4))
assert len(tiles)==6144 and len({bytes(tiles[i*1024:(i+1)*1024]) for i in range(6)})==6
lines=['/* Generated by tools/import_rally_states.py; original Rally hurt/cast/climb art. */','static const u8 sRallyStateTiles[] __attribute__((aligned(4))) = {']
lines += [','.join(str(v) for v in tiles[i:i+32])+',' for i in range(0,len(tiles),32)]+['};']
for frame in range(6):lines.append(f'static const u16 sRallyStateFrame{frame}[] = {{1,0x80c8,0xc1f0,{frame*32},0}};')
lines.append('static const void* const sRallyStateFrames[] = {'+','.join(f'sRallyStateFrame{i}' for i in range(6))+'};')
for frame in range(6):lines.append(f'static const u16 sRallyStateAnim{frame}[] = {{0,0,1,{frame},8}};')
lines.append('static const void* const sRallyStateAnims[] = {'+','.join(f'sRallyStateAnim{i}' for i in range(6))+'};')
(root/'rally_states_data.h').write_text('\n'.join(lines)+'\n')
(root/'states-manifest.json').write_text(json.dumps(dict(source=str(source),source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),frames=6,states=['hurt','cast','climb'],views=['front','rear'],cell=[32,64],foot=[16,56],palette='unchanged sRallyPalette',tiles_bytes=6144,climb='single held pose; no alternation claim'),indent=2)+'\n')
print('Rally states: six distinct poses, unchanged palette, fixed feet, 6144 bytes')
