"""Compile Rally's approved concept poses into native 4bpp OBJ data.
The source remains untouched; outputs use a shared 15-color GBA palette.
"""
from pathlib import Path
from PIL import Image
import hashlib,json
src=Path('tactics/character-assets/pink-ponytail/starter-sheet-v2.png')
out=Path('tactics/character-assets/rally');out.mkdir(exist_ok=True)
im=Image.open(src).convert('RGBA');frames=[]
for row in range(4):
 for col in range(5):
  crop=im.crop((round(col*im.width/5),round(row*im.height/4),round((col+1)*im.width/5),round((row+1)*im.height/4)))
  mask=crop.getchannel('A').point(lambda a:255 if a>=128 else 0)
  crop=crop.crop(mask.getbbox());crop.thumbnail((28,44),Image.Resampling.NEAREST)
  canvas=Image.new('RGBA',(32,64));canvas.alpha_composite(crop,((32-crop.width)//2,56-crop.height));frames.append(canvas)
atlas=Image.new('RGBA',(160,256))
for i,f in enumerate(frames):atlas.alpha_composite(f,((i%5)*32,(i//5)*64))
quant=atlas.convert('RGB').quantize(colors=15,method=Image.Quantize.MEDIANCUT)
pal=quant.getpalette()[:45];gba=[0]+[(pal[i]>>3)|((pal[i+1]>>3)<<5)|((pal[i+2]>>3)<<10) for i in range(0,45,3)]
indexed=Image.new('P',atlas.size);indexed.putpalette([0,0,0]+pal+[0]*(768-48))
indexed.putdata([q+1 if a>=128 else 0 for q,a in zip(quant.getdata(),atlas.getchannel('A').getdata())]);indexed.info['transparency']=0;indexed.save(out/'rally-native.png')
data=[]
for i in range(20):
 x0=(i%5)*32;y0=(i//5)*64
 for ty in range(8):
  for tx in range(4):
   for y in range(8):
    for x in range(0,8,2):data.append(indexed.getpixel((x0+tx*8+x,y0+ty*8+y))|(indexed.getpixel((x0+tx*8+x+1,y0+ty*8+y))<<4))
lines=['/* Generated by tools/import_rally.py; approved Rally draft converted to native OBJ. */', 'static const u16 sRallyPalette[16] = {'+','.join(hex(v) for v in gba)+'};','static const u8 sRallyTiles[] __attribute__((aligned(4))) = {']
lines+= [','.join(str(v) for v in data[i:i+32])+',' for i in range(0,len(data),32)];lines+=['};']
for i in range(20):lines+= [f'static const u16 sRallyFrame{i}[] = {{1,0x80c8,0xc1f0,{i*32},0}};']
lines+=['static const void* const sRallyFrames[] = {'+','.join('sRallyFrame'+str(i) for i in range(20))+'};']
for name,ids in [('Idle',[0]),('Walk',[1,2,3,4]),('Pose',[2,3,2]),('Rise',[1]),('Fall',[4])]:lines+=[f'static const u16 sRally{name}[] = {{0,0,{len(ids)},'+','.join(f'{i},8' for i in ids)+'};']
lines+=['static const void* const sRallyAnims[] = {sRallyIdle,sRallyPose,sRallyWalk,sRallyRise,sRallyFall};']
(out/'rally_data.h').write_text('\n'.join(lines)+'\n')
(out/'manifest.json').write_text(json.dumps(dict(name='Rally',source=str(src),source_sha256=hashlib.sha256(src.read_bytes()).hexdigest(),frames=20,cell=[32,64],foot_anchor=[16,56],palette_entries=16,tiles_bytes=len(data),limitations=['Attack and air poses currently reuse approved walking frames; dedicated action artwork remains needed.']),indent=2)+'\n')
print('Rally: 20 native frames, shared16-entry palette,',len(data),'tile bytes')
