"""Compile original Rally recruitment art to a single 32x32 GBA OBJ.
Deterministic asset compilation only; retain the generated source unchanged.
"""
from pathlib import Path
import hashlib,json
from PIL import Image
root=Path('tactics/character-assets/rally')
source=root/'card-source-v1.png'
im=Image.open(source).convert('RGBA')
mask=im.getchannel('A').point(lambda a:255 if a>=128 else 0)
assert mask.getextrema()[0]==0,'card source requires transparency'
bounds=mask.getbbox();assert bounds
im=im.crop(bounds).resize((32,32),Image.Resampling.NEAREST)
q=im.convert('RGB').quantize(colors=15,method=Image.Quantize.MEDIANCUT)
pal=q.getpalette()[:45]
indexed=Image.new('P',(32,32));indexed.putpalette([0,0,0]+pal+[0]*(768-48))
indexed.putdata([v+1 if a>=128 else 0 for v,a in zip(q.getdata(),im.getchannel('A').getdata())])
indexed.info['transparency']=0;indexed.save(root/'rally-card-native.png')
gba=[0]+[(pal[i]>>3)|((pal[i+1]>>3)<<5)|((pal[i+2]>>3)<<10) for i in range(0,45,3)]
tiles=[]
for ty in range(4):
 for tx in range(4):
  for y in range(8):
   for x in range(0,8,2):tiles.append(indexed.getpixel((tx*8+x,ty*8+y))|(indexed.getpixel((tx*8+x+1,ty*8+y))<<4))
assert len(tiles)==512 and max(indexed.getdata())<16
header=['/* Generated by tools/import_rally_card.py. Original Rally card art. */',
 'static const u16 sRallyCardPalette[16] = {'+','.join(hex(v) for v in gba)+'};',
 'static const u8 sRallyCardTiles[512] __attribute__((aligned(4))) = {']
header += [','.join(str(v) for v in tiles[i:i+32])+',' for i in range(0,512,32)]
header += ['};','static const u16 sRallyCardGfx[] = {1,0x00f0,0x81f0,0,0};']
(root/'rally_card_data.h').write_text('\n'.join(header)+'\n')
(root/'card-manifest.json').write_text(json.dumps({'source':str(source),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'native_size':[32,32],'tiles_bytes':512,'palette_entries':16,'role':'Assembly only; never an in-battle summon action.'},indent=2)+'\n')
print('Rally card: 32x32, 512 OBJ bytes, 16-entry palette')
