"""Compile Rally's approved concept poses into native 4bpp OBJ data.
The source remains untouched; outputs use a shared 15-color GBA palette.
"""
from pathlib import Path
from PIL import Image
import hashlib,json,argparse
parser=argparse.ArgumentParser()
parser.add_argument("--actions",type=Path,default=Path("tactics/character-assets/rally/action-source-v1.png"))
args=parser.parse_args()
src=Path('tactics/character-assets/pink-ponytail/starter-sheet-v2.png')
out=Path('tactics/character-assets/rally');out.mkdir(exist_ok=True)
im=Image.open(src).convert('RGBA');frames=[]
for row in range(4):
 for col in range(5):
  crop=im.crop((round(col*im.width/5),round(row*im.height/4),round((col+1)*im.width/5),round((row+1)*im.height/4)))
  mask=crop.getchannel('A').point(lambda a:255 if a>=128 else 0)
  crop=crop.crop(mask.getbbox());crop.thumbnail((28,44),Image.Resampling.NEAREST)
  canvas=Image.new('RGBA',(32,64));canvas.alpha_composite(crop,((32-crop.width)//2,56-crop.height));frames.append(canvas)
atlas=Image.new('RGBA',(160,256))
for i,f in enumerate(frames):atlas.alpha_composite(f,((i%5)*32,(i//5)*64))
quant=atlas.convert('RGB').quantize(colors=15,method=Image.Quantize.MEDIANCUT)
pal=quant.getpalette()[:45];gba=[0]+[(pal[i]>>3)|((pal[i+1]>>3)<<5)|((pal[i+2]>>3)<<10) for i in range(0,45,3)]
indexed=Image.new('P',atlas.size);indexed.putpalette([0,0,0]+pal+[0]*(768-48))
indexed.putdata([q+1 if a>=128 else 0 for q,a in zip(quant.getdata(),atlas.getchannel('A').getdata())]);indexed.info['transparency']=0
# Compile action art against the existing palette; the original walking
# tiles/palette remain byte-identical. One scale factor preserves body scale
# across windup/strike/recovery/rise/fall rather than enlarging tucked poses.
action_image=Image.open(args.actions).convert('RGBA')
assert action_image.getchannel('A').getextrema()[0]==0, 'action sheet must have transparency'
action_crops=[]
for row in range(2):
 for col in range(5):
  crop=action_image.crop((round(col*action_image.width/5),round(row*action_image.height/2),round((col+1)*action_image.width/5),round((row+1)*action_image.height/2)))
  bounds=crop.getchannel('A').point(lambda a:255 if a>=128 else 0).getbbox()
  assert bounds, 'empty action cell'
  action_crops.append(crop.crop(bounds))
scale=min(44/max(c.height for c in action_crops),32/max(c.width for c in action_crops))
combined=Image.new('P',(160,384));combined.putpalette(indexed.getpalette());combined.paste(indexed,(0,0))
colors=[tuple(pal[i:i+3]) for i in range(0,45,3)]
for frame,crop in enumerate(action_crops):
 crop=crop.resize((max(1,round(crop.width*scale)),max(1,round(crop.height*scale))),Image.Resampling.NEAREST)
 x0=(frame%5)*32+(32-crop.width)//2;y0=(4+frame//5)*64+56-crop.height
 for y in range(crop.height):
  for x in range(crop.width):
   r,g,b,a=crop.getpixel((x,y))
   if a<128:continue
   nearest=min(range(15),key=lambda i:(colors[i][0]-r)**2+(colors[i][1]-g)**2+(colors[i][2]-b)**2)
   combined.putpixel((x0+x,y0+y),nearest+1)
combined.info['transparency']=0;indexed=combined
indexed.save(out/'rally-native.png')
data=[]
for i in range(30):
 x0=(i%5)*32;y0=(i//5)*64
 for ty in range(8):
  for tx in range(4):
   for y in range(8):
    for x in range(0,8,2):data.append(indexed.getpixel((x0+tx*8+x,y0+ty*8+y))|(indexed.getpixel((x0+tx*8+x+1,y0+ty*8+y))<<4))
lines=['/* Generated by tools/import_rally.py; approved Rally draft converted to native OBJ. */', 'static const u16 sRallyPalette[16] = {'+','.join(hex(v) for v in gba)+'};','static const u8 sRallyTiles[] __attribute__((aligned(4))) = {']
lines+= [','.join(str(v) for v in data[i:i+32])+',' for i in range(0,len(data),32)];lines+=['};']
for i in range(30):lines+= [f'static const u16 sRallyFrame{i}[] = {{1,0x80c8,0xc1f0,{i*32},0}};']
lines+=['static const void* const sRallyFrames[] = {'+','.join('sRallyFrame'+str(i) for i in range(30))+'};']
anim_names=[]
for bank in range(4):
 for name,ids in [('Idle',[0]),('Pose',[20,21,22]),('Walk',[1,2,3,4]),('Rise',[23]),('Fall',[24])]:
  symbol=f'sRally{name}{bank}';anim_names.append(symbol)
  lines+=[f'static const u16 {symbol}[] = {{0,0,{len(ids)},'+','.join(f'{i+(bank%2)*5},8' for i in ids)+'};']
lines+=['static const void* const sRallyAnims[] = {'+','.join(anim_names)+'};']
(out/'rally_data.h').write_text('\n'.join(lines)+'\n')
(out/'manifest.json').write_text(json.dumps(dict(name='Rally',source=str(src),source_sha256=hashlib.sha256(src.read_bytes()).hexdigest(),actions_source=str(args.actions),actions_sha256=hashlib.sha256(args.actions.read_bytes()).hexdigest(),frames=30,cell=[32,64],foot_anchor=[16,56],palette_entries=16,tiles_bytes=len(data),limitations=['Opposite-facing draft rows are inconsistent; front/back pair is mirrored for right-facing animation.','Right-facing action and walking banks mirror the authored front/back pair; separate hurt/climb art remains needed.']),indent=2)+'\n')
print('Rally: 30 native frames, shared16-entry palette,',len(data),'tile bytes')
